### ISSUE TITLE
Random personnal Background ?

### ISSUE THREAD

**Issue by MisterCHOUN** [shadowshard4080/firefoxbackground#1]
I wached your video and thanks to you I have been able to change the tab wallpaper with a picture of my own.

Now my question is : Do you know a way to set a random wallpaper when opening a new tab ?

For example, I have p1.jpg and p2.jpg in chrome/img folder,

and I would like to modify the userContent.css to automatically choose one of the two file when opening Firefox/ new tab.

When I asked GPT, I tried to do something like "img/p" + Math.floor(Math.random() * 2) + ".jpg"

But "Math.floor(Math.random() * 2)" does not work in css...

Do you know an another way ?

Regards.

**Comment by shadowshard4080** [comment]
CSS is a static language, so you'd need to use something like Python or JS to modify the CSS file and refresh it in the browser every time a new tab is opened. I'm not even sure if that's possible, but I've considered the possibility myself. I'll let you know if I do end up making something to do that!

**Comment by MisterCHOUN** [comment]
Bonjour,

Thank you for your fast answer,

Now I think about it, I don't spend too much time in fornt of the regular tab since I will jump to another website...

So If I keep one background and I have to change it manually from time to time, it's not that bad overall.


But if you are interested in going a bit further,I will cut my question into 3 propositions :

- 1) Select a random background only when open a new firefox (you will have to close everything to see a new one)

- 2) Select a background depending on the hour (for example if it's 9:AM, the css file will look for the picture number 9)

- 3) Select a random background when opening a new tab.

I will wait patiently for your solution if you find one.

Regards.

**Comment by shadowshard4080** [comment]
In order to do this I'd have to make a Tampermonkey script or make my own extension. If you made it to 4:40 in the video, I outlined an extension with the functionality you want.
